INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (1, 'Chaos', 'Uit Ovidius’ Metamorphosen: Voordat er zee of land was en een lucht die alles toedekt, bestond er slechts één aanschijn der natuur in dit heelal. Men sprak van Chaos, men sprak van Chaos, een primaire ongevormde massa, niet anders dan een bonk gewicht, een samenraapsel van slordige kiemen van niet goed gecombineerde dingen. Er was nog geen Titanenzoon die rondom zonlicht gaf, geen zuster maan die steeds haar nieuwe sikkels vol liet groeien. Er was geen aarde zwevend in omsingelende lucht, op eigen zwaarte balancerend. Amphitrites’ zee had toen nog geen armen rond het lange wereldstrand gelegd. Aarde en zee en lucht, ze waren allemaal wel ergens, maar aarde niet begaanbaar, water niet bevaarbaar nog, en lucht nog onverlicht. Geen element had eigen omtrek en alles zat iets anders dwars, omdat steeds in één ding strijd tussen koud en warm gevoerd werd, tussen droog en vochtig, tussen wat hard en zacht was, tussen zwaar en zwaarteloos.', 'Het Niets');
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (2, 'Gaia', null, 'De Aarde');
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (3, 'Eros', 'Soms wordt gezegd dat Eros de zoon van Chaos is, en op andere momenten weer dat hij de zoon van Ares en Aphrodite is.', 'De Liefde');
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (4, 'Aether', 'Ze wordt ook wel De Atmosfeer genoemd, wat dan slaat op de ''bovenste luchtlaag'', die de goden inademen (in tegenstelling tot de gewone lucht die stervelingen inademen).', 'De Atmosfeer');
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (5, 'Hemera', null, 'De Dag');
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (6, 'Ourea', null, 'De Bergen');
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (7, 'Ouranos', null, 'De Hemel');
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (8, 'Pontus', null, 'De Zee');
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (9, 'Erebos', null, 'God van de Duisternis');
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (10, 'Nyx', null, 'De Nacht');
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (11, 'Chronos', 'Chronos moet niet verward worden met Kronos!', 'De Tijd');
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (12, 'Charon', null, 'Veerman over de Styx');
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (13, 'Typhon', null, 'Reus met honderd vuurspuwende drakenkoppen');
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (14, 'Thanatos', null, 'De Dood');
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (15, 'Tartaros', null, 'De Afgrond');
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (16, 'Okeanos', null, 'Titaan');
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (17, 'Tethys', null, 'Titaan');
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (18, 'Kreios', null, 'Titaan');
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (19, 'Koios', null, 'Titaan');
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (20, 'Phoebe', null, 'Titaan');
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (21, 'Iapetus', null, 'Titaan');
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (22, 'Hyperion', null, 'Titaan');
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (23, 'Theia (Dione)', null, 'Titaan');
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (24, 'Rhea', null, 'Titaan');
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (25, 'Kronos', null, 'Titaan');
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (26, 'Mnemosyne', null, 'Titaan');
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (27, 'Themis', null, 'Titaan');
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (28, 'Nereus', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (29, 'Thaumas', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (30, 'Phorcys', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (31, 'Ceto', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (32, 'Eurybia', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (33, 'Thalassa', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (34, 'Doris', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (35, 'Asopus', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (36, 'Metis', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (37, 'Pleione', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (38, 'Klymene', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (39, 'Perseis', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (40, 'Philyra', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (41, 'Okeaniden', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (42, 'Leto', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (43, 'Asteria', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (44, 'Nereïden', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (45, 'Momus', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (46, 'Hypnos', null, 'De Slaap');
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (47, 'Moros', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (48, 'Nemesis', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (49, 'Apate', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (50, 'Philotes', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (51, 'Geras', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (52, 'Morpheus', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (53, 'Phobetor', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (54, 'Icelus', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (55, 'Phantasos', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (56, 'Helios', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (57, 'Selene', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (58, 'Eos', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (59, 'Hades', null, 'God van de Onderwereld');
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (60, 'Hestia', null, 'Godin van het Huis (controleren)');
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (61, 'Demeter', 'Metamorphosen: Maar toen Saturnus naar de donkere Tartarus verjaagd was en Jupiter de macht had, kwam het zilveren geslacht, slechter dan dat van goud, maar beter dan de bronzen mensen. Jupiter heeft die lang vervlogen lentetijd beperkt, lente werd kort; met winter, zomertij en grillig najaar verdeelde hij het jaar in vier seizoenen na elkaar. Sindsdien lijkt soms de lucht witheet, wanneer zij wordt geblakerd door droge hitte, of hangt het ijs in pegels in de wind. Sindsdien ook dook men weg in huizen --  huizen in de rotswand of in dicht struikgewas of van gevlochten takkenhout. Sindsdien ook wordt het zaad van Ceres in de lange voren goed toegedekt en kreunt de os onder het zware juk.', 'Godin van de Landbouw');
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (62, 'Poseidon', null, 'God van Zee en Wateren');
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (63, 'Hera', null, 'Godin van het Huwelijk');
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (64, 'Zeus', 'Metamorphosen: Maar toen Saturnus naar de donkere Tartarus verjaagd was en Jupiter de macht had, kwam het zilveren geslacht, slechter dan dat van goud, maar beter dan de bronzen mensen. Jupiter heeft die lang vervlogen lentetijd beperkt, lente werd kort; met winter, zomertij en grillig najaar verdeelde hij het jaar in vier seizoenen na elkaar. Sindsdien lijkt soms de lucht witheet, wanneer zij wordt geblakerd door droge hitte, of hangt het ijs in pegels in de wind. Sindsdien ook dook men weg in huizen --  huizen in de rotswand of in dicht struikgewas of van gevlochten takkenhout. Sindsdien ook wordt het zaad van Ceres in de lange voren goed toegedekt en kreunt de os onder het zware juk. -- Theogonie: He is king in Ouranos, holding the thunder and gleaming lightning bolt and after conquering his father Kronos by power.', 'Oppergod van Olympus');
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (65, 'Ares', null, 'God van de Oorlog');
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (66, 'Eileithyia', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (67, 'Hephaistos', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (68, 'Hebe', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (69, 'Circe', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (70, 'Pasiphaë', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (71, 'Aietes', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (72, 'Phaëthon', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (73, 'Epimetheus', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (74, 'Atlas', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (75, 'Menoetius', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (76, 'Prometheus', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (77, 'Artemis', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (78, 'Apollon', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (79, 'Persephone', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (80, 'Hermes', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (81, 'Horen', 'De Horen zijn de godinnen van de seizoenen.', null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (82, 'Muzen', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (83, 'Semele', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (84, 'Dionysos', null, 'God van de Wijn');
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (85, 'Merope', null, 'Pleiade');
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (86, 'Elektra', null, 'Pleiade');
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (87, 'Taygete', null, 'Pleiade');
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (88, 'Alkyone', null, 'Pleiade');
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (89, 'Celaeno', null, 'Pleiade');
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (90, 'Sterope', null, 'Pleiade');
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (91, 'Maia', null, 'Pleiade');
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (92, 'Aphrodite', null, 'Godin van de Liefde');
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (93, 'Eunomia', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (94, 'Hermaphroditus', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (95, 'Peitho', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (96, 'Rhodos', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (97, 'Tyche', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (98, 'Athena', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (99, 'Charybdis', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (100, 'Phobos', null, 'Angst');
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (101, 'Deimos', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (102, 'Anteros', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (103, 'Adrestia', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (104, 'Himeros', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (105, 'Harmonia', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (106, 'Hyrieus', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (107, 'Clonia', null, 'Een nimf');
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (108, 'Nycteus', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (109, 'Lybia', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (110, 'Belus', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (111, 'Agenor', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (112, 'Nilus', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (113, 'Telephassa', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (114, 'Thasos', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (115, 'Phoinix', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (116, 'Cilix', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (117, 'Europa', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (118, 'Kadmos', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (119, 'Ino', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (120, 'Autonoë', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (121, 'Agave', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (122, 'Polydorus', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (123, 'Illyrius', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (124, 'Labdacus', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (125, 'Echion', '', 'Gigant');
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (126, 'Pentheus', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (127, 'Epirus', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (128, 'Aristaeus', '', null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (129, 'Actaeon', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (130, 'Macris', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (131, 'Athamas', '', null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (132, 'Learches', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (133, 'Melicertes', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (134, 'Priapus', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (135, 'Actor', '', null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (136, 'Aegina', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (137, 'Menoetius', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (138, 'Patroclus', 'Interessante persoon om nakomelingen van uit te zoeken?', null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (139, 'Aeacus', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (140, 'Psamathe', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (141, 'Phocus', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (142, 'Endeïs', null, 'Een nimf');
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (143, 'Telamon', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (144, 'Peleus', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (145, 'Periboea', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (146, 'Ajax', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (147, 'Tecmessa', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (148, 'Eurysaces', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (149, 'Thetis', 'Niet te verwarren met de Titaan Thetys', null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (150, 'Achilles', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (151, 'Deidameia', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (152, 'Lycomedes', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (153, 'Neoptolemos', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (154, 'Eetion', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (155, 'Andromache', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (156, 'Hektor', '', null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (157, 'Astyanax', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (158, 'Peramos', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (159, 'Molossos', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (160, 'Pielos', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (161, 'Pluto', 'Pluto was een van de drieduizend zonen en dochters van de Titanen Oceanus en Tethys, oftwel een oceanide.', 'Oceanide');
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (162, 'Tantalos', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (163, 'Broteas', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (164, 'Pelops', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (165, 'Niobe', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (166, 'Oinomaos', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (167, 'Hippodameia', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (168, 'Pittheus', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (169, 'Thyestes', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (170, 'Atreus', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (171, 'Aerope', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (172, 'Anaxibia', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (173, 'Menelaos', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (174, 'Agamemnon', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (175, 'Helena', null, 'Helena van Troje');
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (176, 'Hermione', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (177, 'Paris (Alexandros)', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (178, 'Orestes', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (179, 'Klytaimnestra', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (180, 'Iphigeneia', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (181, 'Elektra', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (182, 'Chrysothemis', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (183, 'Strophios', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (184, 'Pylades', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (185, 'Pelopeia', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (186, 'Aigisthos', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (187, 'Erigone', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (188, 'Aletes', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (189, 'Cassiopeia', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (190, 'Cepheus', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (191, 'Andromeda', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (192, 'Danaë', '', null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (193, 'Perseus', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (194, 'Gorgophone', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (195, 'Perieres', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (196, 'Leucippus', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (197, 'Aphareus', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (198, 'Cynortas', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (199, 'Oebalus', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (200, 'Hippocoon', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (201, 'Icarus', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (202, 'Tyndareos', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (203, 'Periboia', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (204, 'Penelope', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (205, 'Perileos', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (206, 'Odysseus', '', null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (207, 'Leda', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (208, 'Kastor (Castor)', 'Kastor is de tweelingbroer van Polydeuces (Pollux). Het is niet zeker of Kastor geboren is bij Tyndareos, Leda''s echtgenoot, of bij een affaire tussen Leda en Zeus.', null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (209, 'Polydeuces (Pollux)', 'Polydeuces, beter bekend bij zijn Latijnse naam Pollux, is de tweelingbroer van Kastor, zoon van Zeus en Leda en broer van Helena van Troje.', null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (210, 'Kleio', null, 'Muze van de geschiedschrijving');
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (211, 'Euterpe', null, 'Muze van het fluitspel');
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (212, 'Thaleia', null, 'Muze van de komedie');
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (213, 'Melpomene', null, 'Muze van de tragedie');
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (214, 'Terpsichore', 'Muze van de dans en de lyrische poëzie', 'Muze van de dans');
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (215, 'Erato', 'Muze van de hymne, het lied en de lyriek', 'Muze van de hymne');
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (216, 'Polymnia', 'Muze van de retoriek en de gewijde liederen', 'Muze van de retoriek');
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (217, 'Ourania', null, 'Muze van de sterrenkunde');
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (218, 'Kalliope', 'Muze van het heroïsch epos, de filosofie en de retorica. Uit de Theogonie: These things the Muses who have their hall 75 on Olympus, sing, the nine daughters sired by mighty Zeus, Kleio and Euterpe and Thaleia and Melpomene and Terpsichore and Erato and Polymnia and Ourania and Kalliope. The last is the foremost of them all, for she accompanies and attends revered kings.', 'Muze van het epos');
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (220, 'Brontes', null, 'Kykloop');
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (221, 'Steropes', null, 'Kykloop');
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (222, 'Arges', null, 'Kykloop');
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (223, 'Kottos', null, 'Hekatoncheire');
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (224, 'Briareos', null, 'Hekatoncheire');
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (225, 'Gyges', null, 'Hekatoncheire');
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (226, 'Erinyes', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (227, 'Giganten', 'Metamorphosen: Niet slechts de aarde, zelfs de hoge hemel werd onveilig: Giganten vielen de goden aan -- zo wordt verteld -- en stapelden gebergten op elkaar tot sterrenhoogte. Maar toen schoot Jupiter zijn snelle bliksempijl dwars door Olympus’ berg en stootte Pelion van Ossa’s bergrug. De woeste reuzen werden door hun eigen vracht geplet en Moeder Aarde -- zegt men -- werd bevochtigd door het bloed van haar eigen zoons; warm vocht, waaraan zij weer nieuw leven schonk, want om nog enig teken van haar telgen te bewaren deed zij er nieuwe mensen uit ontstaan. Maar ook dat kroost gedroeg zich godsvijandig, was belust op moord en doodslag en vechtziek, onmiskenbaar een uit bloed gesproten ras.', null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (228, 'Meliae', null, 'Nimfen van de Es');
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (229, 'Thanathos', 'Tweelingbroer van Hypnos', 'De Dood');
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (230, 'Oneiroi', null, 'Dromen');
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (231, 'Oizys', null, 'Pijn');
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (232, 'Eris', null, 'Conflict');
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (233, 'Ker', null, 'Destructie/Dood');
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (234, 'Ponos', null, 'Ontbering');
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (235, 'Lethe', null, 'Vergeetachtigheid');
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (236, 'Limos', null, 'Uithongering');
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (237, 'Algae', null, 'Pijn');
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (238, 'Hysminai', null, 'Gevechten');
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (239, 'Makhai', null, 'Oorlogen');
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (240, 'Phonoi', null, 'Moorden');
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (241, 'Androktasiai', null, 'Doodslagen');
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (242, 'Neikea', null, 'Ruzies');
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (243, 'Pseudea', null, 'Leugens');
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (244, 'Logoi', null, 'Verhalen');
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (245, 'Amphillogiai', null, 'Geschillen');
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (246, 'Dysnomia', null, 'Anarchie');
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (247, 'Ate', null, 'Ondergang');
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (248, 'Horkos', null, 'Eed');
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (249, 'Elektra', null, 'Oceanide');
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (250, 'Iris', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (251, 'Harpies', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (252, 'Aello', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (253, 'Okypete', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (254, 'Pemphredo', null, 'Graea');
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (255, 'Enyo', null, 'Graea');
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (256, 'Sthenno', null, 'Gorgo');
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (257, 'Euryale', null, 'Gorgo');
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (258, 'Medusa', null, 'Gorgo');
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (259, 'Chrysaor', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (260, 'Pegasos', null, 'Vliegend paard');
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (261, 'Kallioroe', null, 'Oceanide');
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (262, 'Geryones', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (263, 'Echidna', null, 'Monster');
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (264, 'Orthos', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (265, 'Kerberos', 'De hond van Hades, met 50 hoofden.', 'Hond met 50 hoofden');
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (266, 'Hydra', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (267, 'Herakles', null, 'Held');
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (268, 'Amphitryon', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (269, 'Chimaira', null, 'Monster');
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (270, 'Sphinx', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (271, 'Leeuw van Nemea', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (273, 'Astraios', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (274, 'Pallas', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (275, 'Perses', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (276, 'Zephyr', 'Uit Ovidius'' Metamorphosen: De wereldarchitect gaf aan de winden in het luchtruim geen onbeperkte vrijheid. Maar zelfs dan, -- hoewel zij elk een andere kant op blazen, dreigen zij welhaast ontembaar de wereld stuk te scheuren: zoveel ruzie maken zij, die broers. Eurus verschanst zich bij Aurora in ‘t Arabisch of Perzisch rijk, waar bergland schittert in het ochtendlicht; Zefier woont bij de Avondster, waar stranden zich verwarmen aan dalend zonlicht, en de gruwelijke Boreas raast in het noorden bij de Skythen; ‘t land ertegenover is vochtig door de Auster, niets dan wolk en regenbui.', 'Wind');
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (277, 'Boreas', 'Uit Ovidius'' Metamorphosen: De wereldarchitect gaf aan de winden in het luchtruim geen onbeperkte vrijheid. Maar zelfs dan, -- hoewel zij elk een andere kant op blazen, dreigen zij welhaast ontembaar de wereld stuk te scheuren: zoveel ruzie maken zij, die broers. Eurus verschanst zich bij Aurora in ‘t Arabisch of Perzisch rijk, waar bergland schittert in het ochtendlicht; Zefier woont bij de Avondster, waar stranden zich verwarmen aan dalend zonlicht, en de gruwelijke Boreas raast in het noorden bij de Skythen; ‘t land ertegenover is vochtig door de Auster, niets dan wolk en regenbui.', 'Wind');
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (278, 'Notos', 'Uit Ovidius'' Metamorphosen: De wereldarchitect gaf aan de winden in het luchtruim geen onbeperkte vrijheid. Maar zelfs dan, -- hoewel zij elk een andere kant op blazen, dreigen zij welhaast ontembaar de wereld stuk te scheuren: zoveel ruzie maken zij, die broers. Eurus verschanst zich bij Aurora in ‘t Arabisch of Perzisch rijk, waar bergland schittert in het ochtendlicht; Zefier woont bij de Avondster, waar stranden zich verwarmen aan dalend zonlicht, en de gruwelijke Boreas raast in het noorden bij de Skythen; ‘t land ertegenover is vochtig door de Auster (Notos), niets dan wolk en regenbui.', 'Wind');
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (279, 'Eosphoros', null, 'Wind');
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (280, 'Styx', null, 'Oceanide');
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (281, 'Zelos', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (282, 'Nike', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (283, 'Kratos', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (284, 'Bia', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (285, 'Hekate', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (286, 'Alkmene', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (287, 'Aeolus', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (288, 'Antiope', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (289, 'Amphion', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (290, 'Antaeus', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (291, 'Coronis', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (292, 'Asclepius', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (293, 'Chione', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (294, 'Philammon', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (295, 'Callisto', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (296, 'Arcas', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (297, 'Arestor', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (298, 'Argus', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (299, 'Minos', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (300, 'Ariadne', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (301, 'Autolycus', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (302, 'Oreithuia', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (303, 'Calaïs', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (304, 'Lycaon', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (305, 'Priamos', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (306, 'Cassandra', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (307, 'Daedalion', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (308, 'Clytië', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (309, 'Daedalus', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (310, 'Acrisius', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (311, 'Damasichthon', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (312, 'Deucalion', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (313, 'Tydeus', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (314, 'Diomedes', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (315, 'Dumas', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (316, 'Hecuba', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (317, 'Enaesimus', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (318, 'Io', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (319, 'Epaphus', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (320, 'Erechtheus', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (321, 'Eurymus', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (322, 'Telemus', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (323, 'Galatea', null, 'Nereïde');
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (324, 'Helenus', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (325, 'Hesione', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (326, 'Laomedon', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (327, 'Theseus', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (328, 'Hippolytus', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (329, 'Hippotes', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (330, 'Hyaden', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (331, 'Deianira', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (332, 'Hyllus', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (333, 'Ilioneus', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (334, 'Inachus', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (335, 'Ismenus', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (336, 'Laërtes', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (337, 'Lucifer', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (338, 'Ceyx', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (339, 'Rhea Silvia', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (340, 'Romulus', 'Samen met zijn tweelingbroer Remus oprichter van Rome', null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (341, 'Remus', 'Samen met zijn tweelingbroer Romulus oprichter van Rome', null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (342, 'Miletus', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (343, 'Byblis', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (344, 'Caunis', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (345, 'Androgeos', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (346, 'Misenus', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (347, 'Neleus', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (348, 'Nestor', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (349, 'Oeneus', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (350, 'Meleager', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (351, 'Orpheus', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (352, 'Eurydice', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (353, 'Een Stier', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (354, 'Minotauros', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (355, 'Periklymene', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (356, 'Phaedra', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (358, 'Polyxena', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (359, 'Procris', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (360, 'Kephalos', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (361, 'Pyrrha', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (362, 'Sipylus', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (363, 'Teucer', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (364, 'Aegeus', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (365, 'Amphitrite', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (366, 'Triton', null, null);
INSERT INTO kcv.people (personId, name, description, shortDescription) VALUES (367, 'Zetes', null, null);